services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/src/app
    depends_on:
      - db
    env_file:
      - .env
    # Override the default command from the Dockerfile to ensure hot reload is enabled
    command: ["/bin/bash", "start_backend.sh"]
  admin:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      - db
    env_file:
      - .env
    command: ["/bin/bash", "start_admin_panel.sh"]


volumes:
  postgres_data:
